#!/usr/bin/env python3
"""Regenerate parity-baseline/manifest.yaml from the current fixture contents.

Usage:
  python3 Gaia-framework/test/fixtures/parity-baseline/.regenerate-manifest.py \
      [--tag-sha <sha>] [--capture-date <iso8601>] [--claude-code-version <str>]

Defaults read the current `v-parity-baseline` tag via `git rev-parse`. The
generated manifest uses stable, line-oriented YAML that the sibling `verify.sh`
parses with a stdlib-only Python reader — no pyyaml dependency on the hot path.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys


def sha256_file(path: str) -> tuple[str, int]:
    with open(path, "rb") as f:
        data = f.read()
    return hashlib.sha256(data).hexdigest(), len(data)


def resolve_tag_sha() -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", "Gaia-framework", "rev-parse", "v-parity-baseline^{commit}"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except Exception:
        return "UNRESOLVED"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--tag-sha", default=None)
    p.add_argument("--capture-date", default="2026-04-15T12:00:00Z")
    p.add_argument("--claude-code-version", default="claude-code-2026-04-15")
    p.add_argument("--captured-by", default="jlouage")
    args = p.parse_args()

    repo_root = os.getcwd()
    fixture_rel = "Gaia-framework/test/fixtures/parity-baseline"
    fixture_abs = os.path.join(repo_root, fixture_rel)
    if not os.path.isdir(fixture_abs):
        print(f"error: fixture directory not found: {fixture_abs}", file=sys.stderr)
        return 2

    tag_sha = args.tag_sha or resolve_tag_sha()

    entries: list[tuple[str, str, int]] = []
    for dp, _, fns in os.walk(fixture_abs):
        for fn in sorted(fns):
            if fn in ("manifest.yaml", "verify.sh"):
                continue
            full = os.path.join(dp, fn)
            rel = os.path.relpath(full, repo_root).replace("\\", "/")
            sha, size = sha256_file(full)
            entries.append((rel, sha, size))
    entries.sort(key=lambda e: e[0])

    lines = [
        "# Parity Baseline Manifest",
        "# Generated by E28-S2. DO NOT edit by hand — regenerate via",
        "# python3 Gaia-framework/test/fixtures/parity-baseline/.regenerate-manifest.py",
        "gaia_version: v-parity-baseline",
        f"claude_code_version: {args.claude_code_version}",
        f"capture_date: {args.capture_date}",
        f"captured_by: {args.captured_by}",
        f"tag_sha: {tag_sha}",
        "files:",
    ]
    for path, sha, size in entries:
        lines.append(f"  - path: {path}")
        lines.append(f"    sha256: sha256:{sha}")
        lines.append(f"    size_bytes: {size}")
    content = "\n".join(lines) + "\n"

    out_path = os.path.join(fixture_abs, "manifest.yaml")
    with open(out_path, "w") as f:
        f.write(content)
    print(f"wrote {len(entries)} entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
